### ISSUE TITLE
"An Annotated List of DevOps Technical Interview Questions" is not accessible

### ISSUE THREAD

**Issue by jagub2** [DopplerHQ/awesome-interview-questions#140]
As stated in title, provided link is not working. Looks like the domain wasn't renewed and now it is used as parked domain. Is there any mirror of that link?

**Comment by knayan1** [comment]
This is not only for the given title, but for all the titles that point to "recruityourninja.com". Looking at whois record, I can say that this domain is still active, and we should not delete these links as of now

> Created on 2017-09-22
Expires on 2019-09-22
Updated on 2018-11-02

Other titles that uses this site:
- An Annotated List of Frontend Developer Technical Interview Questions
- An Annotated List of Backend Developer Technical Interview Questions
- An Annotated List of DevOps Technical Interview Questions
- An Annotated List of Data Scientist Technical Interview Questions

**Comment by jagub2** [comment]
I haven't said anything about removing links. I asked for **mirror**. Currently you can see the text "This webpage was generated by the domain owner using Sedo Domain Parking.". Do you really think the website is still maintained?

**Comment by knayan1** [comment]
I agree with you, I've just given my observations, as per whois record.

**Comment by knayan1** [comment]
Will these work for you?
- https://www.edureka.co/blog/interview-questions/top-devops-interview-questions-2016/
- https://intellipaat.com/interview-question/devops-interview-questions/
