### ISSUE TITLE
Can someone please check the links?

### ISSUE THREAD

**Issue by wall03** [DopplerHQ/awesome-interview-questions#195]
I am asking for someone to periodically check the list for bugs (like maybe every few months?), as I am worried some of them are dead

**Comment by bharadwaj-pendyala** [comment]
@wall03 I could develop up a scraper to scan through all the links available and verify if the links/response codes are working as expected? Would that be feasible?

**Comment by wall03** [comment]
That would be great. Thanks!

**Comment by MaximAbramchuck** [comment]
Absolutely, @bharadwaj-pendyala! That'd be great

**Comment by bharadwaj-pendyala** [comment]
@wall03  @MaximAbramchuck  
Developed a basic utility, found below links have been broken/dead. Raised a PR - https://github.com/MaximAbramchuck/awesome-interview-questions/pull/196 for the same.

**Comment by ryan-blunden** [comment]
Fixed by #231

**Comment by ryan-blunden** [comment]
Fixed by #231
