### ISSUE TITLE
Help needed - Integration between SOA and oracle SOA

### ISSUE THREAD

**Issue by olivialiam** [DopplerHQ/awesome-interview-questions#211]
Our client is using github applications for project management and uses ERP for financial management. They want to integrate the projects from github application to ERP. They plan to implement it using SOA services, so can you please help me find the details of integration between SOA suite with **[Oracle SOA](https://smconsultant.com/oracle-soa-tutorial/)**

**Comment by ryan-blunden** [comment]
Sorry @olivialiam, but this repo is for interview questions, not general implementation advice.
