### ISSUE TITLE
go: poor quality article linked

### ISSUE THREAD

**Issue by paralin** [DopplerHQ/awesome-interview-questions#242]
http://career.guru99.com/top-20-go-programming-interview-questions/

This link is very low quality and the answers are in many ways incomplete/incorrect/not relevant. Recommend to remove it.

**Comment by elliotfayman** [comment]
While the quality is low, for some of the sections guru99 is the only public resource for interview questions so I would suggest preserving these resources rather than removing them.

**Comment by imvanzen** [comment]
@paralin I requested an update for this list https://github.com/DopplerHQ/awesome-interview-questions/commit/29efc8bf3f4cff8c2f8514db1a01307acdf7b613

**Comment by paralin** [comment]
The article is of absolute lowest quality (that I linked in the original post here). It's still in the list ages later ..
